### ISSUE TITLE
Weird icon, missing ocntent?

### ISSUE THREAD

**Issue by lfrancis** [cultureondemand/iava-report#15]
https://cultureondemand.github.io/iava-report/#step-6

![womenmissing](https://user-images.githubusercontent.com/6942589/31901208-c689eca6-b7ee-11e7-932e-9694f9ec3424.png)

**Comment by cultureondemand** [comment]
was missing the photo for this screen, is there now

**Comment by lfrancis** [comment]
Confirmed addressed
