### ISSUE TITLE
Screen offset and video presented on aOS 7.1

### ISSUE THREAD

**Issue by lfrancis** [cultureondemand/iava-report#30]
https://cultureondemand.github.io/iava-report/#

The screen is offset and video is unexpectedly presented on aOS 7.1

![aos71](https://user-images.githubusercontent.com/6942589/31908335-7422f1ea-b804-11e7-9420-2650a9de7824.png)

**Comment by cultureondemand** [comment]
gonna have the video issue, spacing fixed

**Comment by lfrancis** [comment]
Confirmed addressed
