### ISSUE TITLE
Use the LANG attribute to identify the language of the page.

### ISSUE THREAD

**Issue by lfrancis** [cultureondemand/iava-report#5]
Use the LANG attribute to identify the language of the page.
WCAG 2.0 A 3.1.1 Section 508 (2017) A 3.1.1
1 pages

In HTML add a LANG attribute to the HTML tag, and in PDF set the language using Document Properties in Acrobat. This allows screen readers to pronounce words correctly.

https://cultureondemand.github.io/iava-report/
Line 2

**Comment by cultureondemand** [comment]
added

**Comment by lfrancis** [comment]
Confirmed addressed
